services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: ${NOME_CONTAINER_API}
    ports:
      - "3030:3030"
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:trainee2024%2F2@localhost:3306/database_projeto"
    command: sh -c "sleep 20 && npx prisma migrate deploy && npm start"
    networks:
      - my_network  # Definindo a rede para este serviço

  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_DB_NAME}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - my_network  # Definindo a rede para este serviço

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge