services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: ${NOME_CONTAINER_API}
    ports:
      - "${PORT_API}:${PORT_API}"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "sleep 20 && npx prisma migrate deploy && npm start"
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_DB_NAME}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge