version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: minha_api
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:trainee2024%2F2@localhost:3306/database_projeto"
    command: sh -c "sleep 20 && npx prisma migrate deploy && npm start"
    networks:
      - my_network  # Definindo a rede para este serviço

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: trainee2024/2
      MYSQL_DATABASE: database_projeto
    networks:
      - my_network  # Definindo a rede para este serviço

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge  # Garantindo que ambos os contêineres usem a mesma rede
