version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: minha_api
    ports:
      - "3030:3030"  # Expondo a porta 3030 para a API
      - "5555:5555"  # Expondo a porta 5555 para o Prisma
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:trainee2024%2F2@mysql:3306/database_projeto"
    command: sh -c "sleep 20 && npx prisma migrate deploy && npm start"
    networks:
      - my_network  # Garantindo que ambos os contêineres usem a mesma rede

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: trainee2024/2
      MYSQL_DATABASE: database_projeto
    networks:
      - my_network  # Garantindo que ambos os contêineres usem a mesma rede

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge  # Garantindo que ambos os contêineres usem a mesma rede
